proxy: fix errors reported by Travis
Symptoms:
```
digest.go:43:30: error strings should not be capitalized (ST1005)
digest.go:46:35: error strings should not be capitalized (ST1005)
digest.go:119:15: the argument is already a string, there's no need to use fmt.Sprintf (S1025)
```