Fix lint errors due to t.Fatal usage
Vet complains when t.Fatal is used in non-test goroutine
```
Error: internal/transport/handler_server_test.go:299:21: call to (*T).Fatal from a non-test goroutine
```